# Generated by Django 3.1.1 on 2020-10-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201012_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sub',
            new_name='desc',
        ),
    ]
