# Generated by Django 3.1.1 on 2020-10-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201013_1419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Categoty',
        ),
        migrations.RemoveField(
            model_name='post',
            name='catagoty',
        ),
        migrations.AddField(
            model_name='post',
            name='categoty',
            field=models.CharField(default='uncategorized', max_length=200),
        ),
    ]
