# Generated by Django 3.1.1 on 2020-10-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201013_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoty',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categoty',
            new_name='Category',
        ),
    ]
