# Generated by Django 3.1.1 on 2020-10-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20201016_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default_post_img.jpg', null=True, upload_to='images/'),
        ),
    ]
